const data = {
	products: [
		{
			_id: '1',
			name: 'Nike Slim Shirt',
			category: 'Shirts',
			image: '/images/p2.jpg',
			price: 120,
			rating: 4.5,
			numReviews: 10,
			brand: 'Nike',
			description: 'high quality product',
		},
		{
			_id: '2',
			name: 'Adidas Fit Shirt',
			category: 'Shirts',
			image: '/images/p3.jpg',
			price: 100,
			rating: 4.0,
			numReviews: 11,
			brand: 'Adidas',
			description: 'high quality product',
		},
		{
			_id: '3',
			name: 'Lacoste Free Pants',
			category: 'Pants',
			image: '/images/p4.jpg',
			price: 180,
			rating: 4.8,
			numReviews: 16,
			brand: 'Lacoste',
			description: 'high quality product',
		},
		{
			_id: '4',
			name: 'Nike Slim Pants',
			category: 'Pants',
			image: '/images/p5.jpg',
			price: 98,
			rating: 4.7,
			numReviews: 38,
			brand: 'Nike',
			description: 'high quality product',
		},
		{
			_id: '5',
			name: 'Puma Slim Pants',
			category: 'Pants',
			image: '/images/p6.jpg',
			price: 73,
			rating: 3.5,
			numReviews: 20,
			brand: 'Puma',
			description: 'high quality product',
		},
		{
			_id: '6',
			name: 'Adidas Slim Shirts',
			category: 'Shirts',
			image: '/images/p7.jpg',
			price: 112,
			rating: 4.5,
			numReviews: 14,
			brand: 'Adidas',
			description: 'high quality product',
		},
	],
};
export default data;
